apiVersion: v1
kind: Service
metadata:
  name: my-app-helm-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-app-helm
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}

